export default {
  FONT_SIZE_S: 14,
  FONT_SIZE_M: 16,
  FONT_SIZE_L: 20,
  FONT_SIZE_XL: 26,
  FONT_SIZE_XXL: 32,
  FONT_SIZE_ICON: 28,

  MAIN_COLOR: '#2a9d9d',
  MAIN_COLOR_LIGHT: '#f2fcfc',
  RIGHT_COLOR: '#6aa84f',
  WRONG_COLOR: '#e30000',
};
