name: Run test suite

on: [pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [24.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable  # Activate Corepack to handle Yarn versions

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Run test command
        run: yarn run test-ci
